pub mod exif_tags {
    pub type ExifTag = u32;

    pub const GPS_VERSION_ID: u32 = 0;
    pub const GPS_LATITUDE_REF: u32 = 1;
    pub const GPS_LATITUDE: u32 = 2;
    pub const GPS_LONGITUDE_REF: u32 = 3;
    pub const GPS_LONGITUDE: u32 = 4;
    pub const GPS_ALTITUDE_REF: u32 = 5;
    pub const GPS_ALTITUDE: u32 = 6;
    pub const GPS_TIME_STAMP: u32 = 7;
    pub const GPS_SATELLITES: u32 = 8;
    pub const GPS_STATUS: u32 = 9;
    pub const GPS_MEASURE_MODE: u32 = 10;
    pub const GPS_DOP: u32 = 11;
    pub const GPS_SPEED_REF: u32 = 12;
    pub const GPS_SPEED: u32 = 13;
    pub const GPS_TRACK_REF: u32 = 14;
    pub const GPS_TRACK: u32 = 15;
    pub const GPS_IMG_DIRECTION_REF: u32 = 16;
    pub const GPS_IMG_DIRECTION: u32 = 17;
    pub const GPS_MAP_DATUM: u32 = 18;
    pub const GPS_DEST_LATITUDE_REF: u32 = 19;
    pub const GPS_DEST_LATITUDE: u32 = 20;
    pub const GPS_DEST_LONGITUDE_REF: u32 = 21;
    pub const GPS_DEST_LONGITUDE: u32 = 22;
    pub const GPS_DEST_BEARING_REF: u32 = 23;
    pub const GPS_DEST_BEARING: u32 = 24;
    pub const GPS_DEST_DISTANCE_REF: u32 = 25;
    pub const GPS_DEST_DISTANCE: u32 = 26;
    pub const GPS_PROCESSING_METHOD: u32 = 27;
    pub const GPS_AREA_INFORMATION: u32 = 28;
    pub const GPS_DATE_STAMP: u32 = 29;
    pub const GPS_DIFFERENTIAL: u32 = 30;
    pub const GPS_H_POSITIONING_ERROR: u32 = 31;

    pub const INTEROPERABILITY_INDEX: ExifTag = 1;
    pub const INTEROPERABILITY_VERSION: ExifTag = 2;
    pub const NEW_SUBFILE_TYPE: ExifTag = 254;
    pub const IMAGE_WIDTH: ExifTag = 256;
    pub const IMAGE_LENGTH: ExifTag = 257;
    pub const BITS_PER_SAMPLE: ExifTag = 258;
    pub const COMPRESSION: ExifTag = 259;
    pub const PHOTOMETRIC_INTERPRETATION: ExifTag = 262;
    pub const FILL_ORDER: ExifTag = 266;
    pub const DOCUMENT_NAME: ExifTag = 269;
    pub const IMAGE_DESCRIPTION: ExifTag = 270;
    pub const MAKE: ExifTag = 271;
    pub const MODEL: ExifTag = 272;
    pub const STRIP_OFFSETS: ExifTag = 273;
    pub const ORIENTATION: ExifTag = 274;
    pub const SAMPLES_PER_PIXEL: ExifTag = 277;
    pub const ROWS_PER_STRIP: ExifTag = 278;
    pub const STRIP_BYTE_COUNTS: ExifTag = 279;
    pub const X_RESOLUTION: ExifTag = 282;
    pub const Y_RESOLUTION: ExifTag = 283;
    pub const PLANAR_CONFIGURATION: ExifTag = 284;
    pub const RESOLUTION_UNIT: ExifTag = 296;
    pub const TRANSFER_FUNCTION: ExifTag = 301;
    pub const SOFTWARE: ExifTag = 305;
    pub const DATE_TIME: ExifTag = 306;
    pub const ARTIST: ExifTag = 315;
    pub const WHITE_POINT: ExifTag = 318;
    pub const PRIMARY_CHROMATICITIES: ExifTag = 319;
    pub const SUB_IFDS: ExifTag = 330;
    pub const TRANSFER_RANGE: ExifTag = 342;
    pub const JPEG_PROC: ExifTag = 512;
    pub const JPEG_INTERCHANGE_FORMAT: ExifTag = 513;
    pub const JPEG_INTERCHANGE_FORMAT_LENGTH: ExifTag = 514;
    pub const YCBCR_COEFFICIENTS: ExifTag = 529;
    pub const YCBCR_SUB_SAMPLING: ExifTag = 530;
    pub const YCBCR_POSITIONING: ExifTag = 531;
    pub const REFERENCE_BLACK_WHITE: ExifTag = 532;
    pub const XML_PACKET: ExifTag = 700;
    pub const RELATED_IMAGE_FILE_FORMAT: ExifTag = 4096;
    pub const RELATED_IMAGE_WIDTH: ExifTag = 4097;
    pub const RELATED_IMAGE_LENGTH: ExifTag = 4098;
    pub const IMAGE_DEPTH: ExifTag = 32997;
    pub const CFA_REPEAT_PATTERN_DIM: ExifTag = 33421;
    pub const CFA_PATTERN: ExifTag = 33422;
    pub const BATTERY_LEVEL: ExifTag = 33423;
    pub const COPYRIGHT: ExifTag = 33432;
    pub const EXPOSURE_TIME: ExifTag = 33434;
    pub const FNUMBER: ExifTag = 33437;
    pub const IPTC_NAA: ExifTag = 33723;
    pub const IMAGE_RESOURCES: ExifTag = 34377;
    pub const EXIF_IFD_POINTER: ExifTag = 34665;
    pub const INTER_COLOR_PROFILE: ExifTag = 34675;
    pub const EXPOSURE_PROGRAM: ExifTag = 34850;
    pub const SPECTRAL_SENSITIVITY: ExifTag = 34852;
    pub const GPS_INFO_IFD_POINTER: ExifTag = 34853;
    pub const ISO_SPEED_RATINGS: ExifTag = 34855;
    pub const OECF: ExifTag = 34856;
    pub const TIME_ZONE_OFFSET: ExifTag = 34858;
    pub const SENSITIVITY_TYPE: ExifTag = 34864;
    pub const STANDARD_OUTPUT_SENSITIVITY: ExifTag = 34865;
    pub const RECOMMENDED_EXPOSURE_INDEX: ExifTag = 34866;
    pub const ISO_SPEED: ExifTag = 34867;
    pub const ISO_SPEED_LATITUDEYYY: ExifTag = 34868;
    pub const ISO_SPEED_LATITUDEZZZ: ExifTag = 34869;
    pub const EXIF_VERSION: ExifTag = 36864;
    pub const DATE_TIME_ORIGINAL: ExifTag = 36867;
    pub const DATE_TIME_DIGITIZED: ExifTag = 36868;
    pub const OFFSET_TIME: ExifTag = 36880;
    pub const OFFSET_TIME_ORIGINAL: ExifTag = 36881;
    pub const OFFSET_TIME_DIGITIZED: ExifTag = 36882;
    pub const COMPONENTS_CONFIGURATION: ExifTag = 37121;
    pub const COMPRESSED_BITS_PER_PIXEL: ExifTag = 37122;
    pub const SHUTTER_SPEED_VALUE: ExifTag = 37377;
    pub const APERTURE_VALUE: ExifTag = 37378;
    pub const BRIGHTNESS_VALUE: ExifTag = 37379;
    pub const EXPOSURE_BIAS_VALUE: ExifTag = 37380;
    pub const MAX_APERTURE_VALUE: ExifTag = 37381;
    pub const SUBJECT_DISTANCE: ExifTag = 37382;
    pub const METERING_MODE: ExifTag = 37383;
    pub const LIGHT_SOURCE: ExifTag = 37384;
    pub const FLASH: ExifTag = 37385;
    pub const FOCAL_LENGTH: ExifTag = 37386;
    pub const SUBJECT_AREA: ExifTag = 37396;
    pub const TIFF_EP_STANDARD_ID: ExifTag = 37398;
    pub const MAKER_NOTE: ExifTag = 37500;
    pub const USER_COMMENT: ExifTag = 37510;
    pub const SUB_SEC_TIME: ExifTag = 37520;
    pub const SUB_SEC_TIME_ORIGINAL: ExifTag = 37521;
    pub const SUB_SEC_TIME_DIGITIZED: ExifTag = 37522;
    pub const XP_TITLE: ExifTag = 40091;
    pub const XP_COMMENT: ExifTag = 40092;
    pub const XP_AUTHOR: ExifTag = 40093;
    pub const XP_KEYWORDS: ExifTag = 40094;
    pub const XP_SUBJECT: ExifTag = 40095;
    pub const FLASH_PIX_VERSION: ExifTag = 40960;
    pub const COLOR_SPACE: ExifTag = 40961;
    pub const PIXEL_X_DIMENSION: ExifTag = 40962;
    pub const PIXEL_Y_DIMENSION: ExifTag = 40963;
    pub const RELATED_SOUND_FILE: ExifTag = 40964;
    pub const INTEROPERABILITY_IFD_POINTER: ExifTag = 40965;
    pub const FLASH_ENERGY: ExifTag = 41483;
    pub const SPATIAL_FREQUENCY_RESPONSE: ExifTag = 41484;
    pub const FOCAL_PLANE_X_RESOLUTION: ExifTag = 41486;
    pub const FOCAL_PLANE_Y_RESOLUTION: ExifTag = 41487;
    pub const FOCAL_PLANE_RESOLUTION_UNIT: ExifTag = 41488;
    pub const SUBJECT_LOCATION: ExifTag = 41492;
    pub const EXPOSURE_INDEX: ExifTag = 41493;
    pub const SENSING_METHOD: ExifTag = 41495;
    pub const FILE_SOURCE: ExifTag = 41728;
    pub const SCENE_TYPE: ExifTag = 41729;
    pub const NEW_CFA_PATTERN: ExifTag = 41730;
    pub const CUSTOM_RENDERED: ExifTag = 41985;
    pub const EXPOSURE_MODE: ExifTag = 41986;
    pub const WHITE_BALANCE: ExifTag = 41987;
    pub const DIGITAL_ZOOM_RATIO: ExifTag = 41988;
    pub const FOCAL_LENGTH_IN_35MM_FILM: ExifTag = 41989;
    pub const SCENE_CAPTURE_TYPE: ExifTag = 41990;
    pub const GAIN_CONTROL: ExifTag = 41991;
    pub const CONTRAST: ExifTag = 41992;
    pub const SATURATION: ExifTag = 41993;
    pub const SHARPNESS: ExifTag = 41994;
    pub const DEVICE_SETTING_DESCRIPTION: ExifTag = 41995;
    pub const SUBJECT_DISTANCE_RANGE: ExifTag = 41996;
    pub const IMAGE_UNIQUE_ID: ExifTag = 42016;
    pub const CAMERA_OWNER_NAME: ExifTag = 42032;
    pub const BODY_SERIAL_NUMBER: ExifTag = 42033;
    pub const LENS_SPECIFICATION: ExifTag = 42034;
    pub const LENS_MAKE: ExifTag = 42035;
    pub const LENS_MODEL: ExifTag = 42036;
    pub const LENS_SERIAL_NUMBER: ExifTag = 42037;
    pub const COMPOSITE_IMAGE: ExifTag = 42080;
    pub const SOURCE_IMAGE_NUMBER_OF_COMPOSITE_IMAGE: ExifTag = 42081;
    pub const SOURCE_EXPOSURE_TIMES_OF_COMPOSITE_IMAGE: ExifTag = 42082;
    pub const GAMMA: ExifTag = 42240;
    pub const PRINT_IMAGE_MATCHING: ExifTag = 50341;
    pub const PADDING: ExifTag = 59932;
}
/// Represents an EXIF ifd. Ifd0 is the primary image and contains techical specs about the
/// image, Ifd1 is the thumbnail, and IfdExif contains info about the camera settings for example.
#[repr(u8)]
pub enum ExifIfd {
    /// Primary image. Contains tags about the image dimensions for example.
    Ifd0 = 0,
    /// The thumbnail. Contain the same tags as Ifd0, but their values are about the thumbnail.
    Ifd1 = 1,
    /// General tags about camera settings for example.
    IfdExif = 2,
    /// Contains GPS tags
    IfdGps = 3,
    IfdInteroperability = 4,
    IfdCount = 5,
}
